extends Label

var death_messages = ["Whoops.",
	"That wasn't supposed to happen...",
	"My bad.",
	"Get one shotted lol",
	"Git gud",
	"Please try again later.",
	"Skill issue?",
	"You look dumb now, don't you?",
	"Dev needs to fix this",
	"GG ez",
	"That's all?",
	"Time to repeat the process.",
	"Here we go again...",
	"Try not to do that again next time.",
	"Clearly, something happened that lead to your death.",
	"Are you okay?",
	"You'll recover. Someday.",
	"This is the part where you yell at your screen.",
	":clown:",
	"Why did you do that?",
	"Bro...",
	"Seriously?",
	"Well...",
	"Yikes.",
	"This is embarrassing.",
	"Try not to ragequit.",
	"Lol",
	"Hahaha",
	"That didn't work out.",
	"Learn from your mistakes.",
	"Mission failed. We'll get 'em next time.",
	"Spartans never die. They just go M.I.A.",
	"Ouch.",
	"That's... bad...",
	"Task failed successfully.",
	"K.O.!",
	"Wipeout!",
	"FATALITY",
	"Oof",
	"Why?",
	"Stop. Doing. That.",
	"-15 respect",
	"That must've hurt.",
	"What an ePiC fAiL",
	"Return by death.",
	"Were you expecting something?",
	"What did you expect?",
	"You died.",
	"WASTED",
	"OBLITERATED",
	"BRUTALITY",
	"Objective failed.",
	"That happened.",
	"Things aren't looking so bright.",
	"Not everything is sunshine and rainbows, by the way.",
	"Eliminated.",
	"Respawning...",
	"AAAAHHHHHHHHH",
	"Welp.",
	"There is an unnecessary amount of death lines in this game.",
	"Wanna hear a joke?",
	"Tip: Don't die.",
	"Have you tried NOT dying?",
	":god me",
	"/kill all ... Oh, it worked.",
	"The end.",
	"FIN",
	"Hello, player.",
	"Good thing that I placed a bed for you to respawn at.",
	"Take #2!",
	"Alt+F4 to close your game. Just a useful reminder.",
	"Time to unplug the router...",
	"Please don't smash your monitor.",
	"Your safety isn't guaranteed ¯\\_(ツ)_/¯",
	"Not everything goes well in this game.",
	"Perhaps I should nerf that...",
	"Wrong button.",
	"Misclick?",
	"I know. It's not your computer. It's not lag. Or is it?",
	"Pfft.",
	"You died that easily?",
	"I expected a little more, but okay.",
	"Aaaaand that's a wrap.",
	"That's all, folks!",
	"Unlock God Mode for $49.99.",
	"Vibe check.",
	"Oops.",
	"That was a mistake.",
	"I guess I forgot to remove that.",
	"Good game.",
	"Simon says... rejoin!",
	"Got you!",
	"I'm honestly running out of ideas.",
	"What do I put here again?",
	"Sample text here",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam est nisl, posuere vitae lacus a, mattis ornare dui. Nunc consequat.",
	"Looking for something?",
	"You're back!",
	"Sorry.",
	"You died.",
	"You'd still be alive if it weren't for [INSERT TEXT HERE]",
	"FYI, you didn't have to die.",
	"bad",
	"noob",
	"Next time.",
	"Looks like somebody isn't getting their Winner Winner Chicken Dinner.",
	"Alright, what happened now?",
	"Get up on your feet.",
	"Sigh... do you want me to turn on Baby Mode?",
	"'Tis but a wound.",
	"From zero to hero and then back to zero.",
	"How... unfortunate.",
	"I am inevitable.",
	"Cut!",
	"You're worse than hitler",
	"Bro got nerfed"]

# Called when the node enters the scene tree for the first time.
func _ready():
	text = "Score: " + str(GlobalVars.score) + "\n" + death_messages[randi_range(0,death_messages.size() - 1)]
